name: Publish Terraform Module
description: Tags branches and publishes Terraform modules to the Terraform Registry
author: https://github.com/jvrck
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
