#!/bin/bash

set -xeu

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

PL="
steps:\\n
\t- wait\\n
\t- command: \"echo Deploy!\"\\n
\t\tlabel: \":rocket:\"\\n
\t\tagents:\\n
\t\t\tqueue: \"default\"\\n
"

echo -e $PL | buildkite-agent pipeline upload