#!/bin/bash

set -xeuo pipefail

function format_url() {
  local url=$1
  url=${url//\//-}   # Replace '/' with '-'
  url=${url//\./-}   # Replace '.' with '-'
  url=${url//#/-}    # Replace '#' with '-'
  echo "$url"
}

export TFC_PLUGIN_URL=$(echo "$BUILDKITE_PLUGINS" | jq -r '.[] | select(. | keys[] | contains("github.com/jvrck/terraform-publish-module-buildkite-plugin")) | keys[]')

export TFC_PLUGIN_PATH=$(format_url "$TFC_PLUGIN_URL")

export TFC_PLUGIN_PIPELINE_PATH=${BUILDKITE_PLUGINS_PATH}/${TFC_PLUGIN_PATH}/hooks/plugin-pipeline.yml

export TAG_SCRIPT_PATH=${BUILDKITE_PLUGINS_PATH}/${TFC_PLUGIN_PATH}/hooks/tag.sh
