#!/bin/bash

set -xeu

# echo "  - wait"
# echo "  - command: \"echo Deploy!\""
# echo "    label: \":rocket:\""
# echo "    agents:"
# echo "      queue: \"default\""

# echo $PWD

# SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# echo $SCRIPT_DIR

# echo  ${SCRIPT_DIR}/plugin-pipeline.yml


# PL="
# steps:\\n
# \t- wait\\n
# \t- command: \"echo Deploy!\"\\n
# \t\tlabel: \":rocket:\"\\n
# \t\tagents:\\n
# \t\t\tqueue: \"default\"\\n
# "
# cat << EndOfMessage
# This is line 1.
# This is line 2.
# Line 3.
# EndOfMessage

# # read -r -d '' VAR <<- EOM
# steps:
#     - wait
#     - command: "echo Deploy!"
#         label: ":rocket:"
#         agents:
#         queue: "default"
# # EOM

USAGE=$(cat <<-END
steps:
    - wait
    - command: "echo Deploy!"
        label: ":rocket:"
        agents:
        queue: "default"
END
)

echo "$USAGE"

buildkite-agent pipeline upload .buildkite/plugin-pipeline.yml