#!/bin/bash

set -eu

echo "  - wait"
echo "  - command: \"echo Deploy!\""
echo "    label: \":rocket:\""
echo "    agents:"
echo "      queue: \"default\""

echo $PWD

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

echo $SCRIPT_DIR

echo  ${SCRIPT_DIR}/plugin-pipeline.yml


PL="
- wait\\n
- command: \"echo Deploy!\"\\n
  label: \":rocket:\"\\n
  agents:\\n
    queue: \"default\"\\n
"

echo -e $PL